const photos=["photo-01.jpeg","photo-02.jpeg","photo-03.jpeg","photo-04.jpeg","photo-05.jpeg","photo-06.jpeg","photo-07.jpeg","photo-08.jpeg","photo-09.jpeg","photo-10.jpeg","photo-11.jpeg","photo-12.jpeg","photo-13.jpeg"];
const reasons=[["Your hardworking nature","You never shy away from putting in the effort to make things better."],["Your sense of responsibility","You take responsibilities head-on instead of running away from them."],["Your caring heart","You genuinely care about the people who matter to you."],["The way you love your family","Family is not just important to you; it is part of who you are."],["Your reliability","Knowing that I can count on you means more than you probably realize."],["Your determination","When something matters to you, you give it your best."],["Your protective nature","There is something comforting about knowing you look out for the people you love."],["Your strength","You carry so much on your shoulders and keep moving forward."],["Your little gestures","Sometimes the smallest things you do say more than a thousand words."],["Your sincerity","I love that the way you care is genuine."],["Your patience","You know how to keep going even when things do not go according to plan."],["Your practical side","You have a way of looking at situations realistically and finding a way forward."],["The way you make life easier","You bring a sense of comfort and organization into my life."],["Your family-first heart","The importance you give your family is something I truly admire."],["Your commitment","When you care about something, you do not give up easily."],["Your thoughtful side","Your actions often say what words do not."],["Your ability to make me comfortable","Being around you feels like being where I belong."],["The husband you are","You take our life and our responsibilities seriously."],["Your sense of humour","Even your unexpected jokes can make an ordinary day more fun. 😂"],["Your jolly side","I love seeing your playful side come out."],["The way you keep trying","No matter how difficult something becomes, you keep pushing forward."],["Your dedication","You give your time and energy to the things that matter."],["Your dependable nature","You are someone I know I can lean on."],["The comfort you bring","You have made ordinary days feel a little more peaceful."],["The way you take care of things","You have a natural instinct to make sure things are taken care of."],["Your ambition","I love seeing you work toward building a good life."],["Your character","Who you are every day matters more than appearances."],["Your love","The way you care makes me grateful to have you as my husband."],["The peace you bring","You have helped make my life feel more settled and comfortable."],["Simply... YOU","After everything I could list, the biggest reason is simply that you are you — and I love you for exactly that. ❤️"]];
const wall=document.getElementById("photoWall");
photos.forEach((p,i)=>{const c=document.createElement("div");c.className="photo-card";c.style.transitionDelay=i*70+"ms";c.innerHTML=`<img src="images/${p}" alt="Birthday memory ${i+1}" loading="lazy">`;c.onclick=()=>openLightbox(`images/${p}`);wall.appendChild(c)});
const grid=document.getElementById("reasonsGrid");
reasons.forEach((r,i)=>{const c=document.createElement("article");c.className="reason";c.style.transitionDelay=i%3*90+"ms";c.innerHTML=`<div class="reason-num">${String(i+1).padStart(2,"0")}</div><h3>${r[0]}</h3><p>${r[1]}</p>`;grid.appendChild(c)});
document.getElementById("finalPhoto").src=`images/${photos[photos.length-1]}`;
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12,rootMargin:"0px 0px -35px 0px"});
document.querySelectorAll(".reveal,.photo-card,.reason").forEach(e=>observer.observe(e));
window.addEventListener("scroll",()=>{const h=document.documentElement.scrollHeight-innerHeight;document.getElementById("progress").style.width=(h>0?scrollY/h*100:0)+"%"});
function openLightbox(src){document.getElementById("lightboxImg").src=src;document.getElementById("lightbox").classList.add("show")}
function closeLightbox(){document.getElementById("lightbox").classList.remove("show")}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeLightbox()});
let lastHeart=0;document.addEventListener("pointermove",e=>{let n=Date.now();if(n-lastHeart<140||Math.random()>.65)return;lastHeart=n;let h=document.createElement("span");h.className="heart-float";h.textContent=Math.random()>.5?"♥":"✦";h.style.left=e.clientX+"px";h.style.top=e.clientY+"px";document.body.appendChild(h);setTimeout(()=>h.remove(),4000)});
const cursor=document.getElementById("cursorGlow");window.addEventListener("pointermove",e=>{cursor.style.left=e.clientX+"px";cursor.style.top=e.clientY+"px"});
const fp=document.getElementById("finalParticles");for(let i=0;i<24;i++){let s=document.createElement("span");s.className="spark";s.style.left=Math.random()*100+"%";s.style.top=65+Math.random()*35+"%";s.style.animationDelay=Math.random()*5+"s";s.style.animationDuration=4+Math.random()*4+"s";fp.appendChild(s)}
const fs=document.querySelector(".final"),fo=new IntersectionObserver(es=>{if(es[0].isIntersecting){launchFireworks();setTimeout(launchFireworks,700);setTimeout(launchFireworks,1400)}},{threshold:.3});fo.observe(fs);
function launchFireworks(){const box=document.getElementById("finalParticles");const burst=document.createElement("div");let x=20+Math.random()*60,y=15+Math.random()*35;burst.style.cssText=`position:absolute;left:${x}%;top:${y}%;width:4px;height:4px;border-radius:50%;background:#e4c481`;for(let i=0;i<18;i++){let p=document.createElement("i"),a=2*Math.PI*i/18,d=45+Math.random()*60;p.style.cssText=`position:absolute;left:0;top:0;width:3px;height:3px;border-radius:50%;background:#e4c481;animation:burst .9s ease-out forwards;--x:${Math.cos(a)*d}px;--y:${Math.sin(a)*d}px`;burst.appendChild(p)}box.appendChild(burst);setTimeout(()=>burst.remove(),1000)}
const st=document.createElement("style");st.textContent="@keyframes burst{to{transform:translate(var(--x),var(--y));opacity:0}}";document.head.appendChild(st);
